# Generated by Django 5.0.3 on 2024-03-10 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('flag', models.ImageField(null=True, upload_to='flags/', verbose_name='Bandera')),
                ('shield', models.ImageField(null=True, upload_to='shields/', verbose_name='Escudo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.CharField(max_length=300, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'Posición',
                'verbose_name_plural': 'Posiciones',
                'db_table': 'position',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=50, verbose_name='Apellido')),
                ('birthday', models.DateField(verbose_name='Fecha de nacimiento')),
                ('nacionality', models.CharField(max_length=50, verbose_name='Nacionalidad')),
                ('Rol', models.CharField(max_length=50, verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Tecnico',
                'verbose_name_plural': 'Tecnicos',
                'db_table': 'tecnico',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=50, verbose_name='Apellido')),
                ('photo', models.ImageField(null=True, upload_to='players/', verbose_name='Foto')),
                ('birthday', models.DateField(verbose_name='Fecha de nacimiento')),
                ('number', models.IntegerField(verbose_name='Número de camiseta')),
                ('holder', models.BooleanField(verbose_name='Titular')),
                ('Equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipo')),
                ('Position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.position')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'db_table': 'jugadores',
                'ordering': ['id'],
            },
        ),
    ]
